apiVersion: v1
kind: Pod
metadata:
  name: pg-client
spec:
  containers:
    - image: radondb-postgresql:15.0-v1.1.0
      name: pg-client
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
